version: "3.8"
services:
  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: modsenTest

  app:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:123@postgres:5432/modsenTest
    ports:
      - "3003:3000"
    volumes:
      - ./prisma:/modsen_prac/prisma
      - ./src:/modsen_prac/src
      - .env:/modsen_prac/.env
    env_file:
      - .env